locations/controllers/LocationController.php
<?php

namespace app\controllers;

class LocationController extends \yii\web\Controller
{
    const DEFAULT_RADIUS = "5km";
    const DEFAULT_LAT = 44.8160;
    const DEFAULT_LONG = 20.4602;
    const DEFAULT_PER_PAGE = 10;
    const DEFAULT_FILTER = '_all';

    /**
     * Action that deals with creation of an item.
     * 
     * @return string
     */
    public function actionCreate()
    {
        $model = new \app\models\Location();

        if (\Yii::$app->request->isPost) {
            $model->load(\Yii::$app->request->post());
            $model->setIsApproved(false);
            if ($model->index()) {
                $this->redirect('/location/index');
            }
        }

        return $this->render('create', array('model' => $model));
    }

    /**
     * Action that deals with displaying items.
     * 
     * @return string
     */
    public function actionIndex()
    {
        $model = new \app\models\Location();

        $latLng = array(
            'latitude' => self::DEFAULT_LAT,
            'longitude' => self::DEFAULT_LONG
        );
        if (\Yii::$app->request->get('latitude', false)) {
            $latLng['latitude'] = \Yii::$app->request->get('latitude', false);
        }
        if (\Yii::$app->request->get('longitude', false)) {
            $latLng['longitude'] = \Yii::$app->request->get('longitude', false);
        }
        // set all default values here
        $locations = $model->getLocations(
            \Yii::$app->request->get('query', ''),
            $latLng,
            \Yii::$app->request->get('radius', self::DEFAULT_RADIUS),
            \Yii::$app->request->get('page', 1),
            \Yii::$app->request->get('perPage', self::DEFAULT_PER_PAGE),
            \Yii::$app->request->get('isApproved', null),
            \Yii::$app->request->get('filter', self::DEFAULT_FILTER)
        );

        return $this->render('index', array(
            'locations' => $locations
        ));
    }

    /**
     * Action that deals with updating of an item.
     * 
     * @return string
     */
    public function actionUpdate()
    {
        $model = \app\models\Location::getLocation(\Yii::$app->request->get('locationId', null));

        if (\Yii::$app->request->isPost) {
            $model->load(\Yii::$app->request->post());
            $model->setIsApproved(true);
            if ($model->index()) {
                $this->redirect('/location/index');
            }
        }

        return $this->render('update', array('model' => $model));
    }

    /**
     * Action that deals with deleting an item.
     * 
     * @return Response
     */
    public function actionDelete()
    {
        $model = \app\models\Location::getLocation(\Yii::$app->request->get('locationId', null));
        $model->delete();
        \Yii::$app->session->addFlash('app', 'Item deleted successfully');
        $this->redirect('/location/index');
    }
}

locations/views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'PHP Srbija - Elasticsearch tutorijal',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    ['label' => 'List', 'url' => ['/location/index']],
                    ['label' => 'Create', 'url' => ['/location/create']],
                ],
            ]);
            NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>

            <?php if (\Yii::$app->session->hasFlash('app')): ?>
            <ul>
                <?php foreach (\Yii::$app->session->getFlash('app') as $message): ?>
                <li><?=$message?></li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>

            <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left"><?= date('Y') ?></p>
            <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>